
- name: Fetch public key
  shell: "nova keypair-show ansible | awk -F ':' '/Public key:/ {print $NF}'"
  environment: "{{ openstack_user_auth_env }}"
  register: public_key
  delegate_to: localhost
  tags:
    - cloud-user-keys

- name: Add {{ key_name }} public key to authorized_keys for cloud-user
  authorized_key:
    user: cloud-user
    state: present
    key: "{{ public_key.stdout }}"
  tags:
    - cloud-user-keys

- name: Install private key
  copy:
    content: "{{ key_content }}"
    dest: "/home/cloud-user/.ssh/id_rsa"
    mode: 0600
    owner: cloud-user
    group: cloud-user
  tags:
    - cloud-user-keys
    
