---


- name: Check Services are running
  command: "/usr/bin/systemctl show openstack-nova-compute --property ActiveState"
  become: true
  register: nova_status_result
  changed_when: False
  ignore_errors: true
  tags:
    - undercloud-install
    - undercloud
    - rebuild

- name: Reboot ospd instance to restart the dbus if undercloud is not running
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  become: true
  when: nova_status_result.stdout_lines | last == "ActiveState=inactive"
  tags:
    - undercloud-install
    - undercloud
    - rebuild

- name: Wait for the ospd instance reboot to complete
  wait_for:
    port: 22
    host: "{{ hostvars['localhost']['ospd_ip'] }}"
    search_regex: "OpenSSH"
    delay: 10
  delegate_to: localhost
  when: nova_status_result.stdout_lines | last == "ActiveState=inactive"
  tags:
    - undercloud-install
    - undercloud
    - rebuild

- name: Ensure undercloud is {{ new_state }}
  shell: >
    set -o pipefail &&
    openstack undercloud install &>
    /home/stack/undercloud_install.log
  become: yes
  become_user: stack
  when: nova_status_result.stdout_lines | last == "ActiveState=inactive"
  async: 3600
  poll: 20
  tags:
    - undercloud-install
    - undercloud
    - rebuild
