---
- name: set the ospd_float fact
  set_fact:
    ospd_ip: "{{ networks['external'].cidr_prefix }}.{{ last_octet['ospd']['ospd_1'] }}"
  tags:
    - ospd-inventory

- name: Ensure the bastion instance is {{ new_state }} in the bastion group
  add_host:
    hostname: "{{ prefix}}-ospd-1"
    ansible_ssh_host: "{{ ospd_ip }}"
    ansible_ssh_user: cloud-user
    become_user: root
    become_method: sudo
    groups:
      - ospd
      - all
  tags:
    - ospd-inventory

- name: Wait for the ospd instance to become accessable
  wait_for:
    port: 22
    host: "{{ prefix }}-ospd-1"
    search_regex: "OpenSSH"
    delay: 10
  tags:
    - ospd-inventory
