---
- name: Ensure support for fake_pxe in ironic is {{ new_state }}
  lineinfile:
    path: /etc/ironic/ironic.conf
    state: "{{ new_state }}"
    regexp: '^enabled_drivers\s'
    line: 'enabled_drivers = pxe_ipmitool,pxe_ssh,pxe_drac,pxe_ilo,fake_pxe'
  notify:
    - restart_ironic
  tags: 
    - ironic-config
    - undercloud

- name: Move the ipmitool binary to a backup
  copy:
    remote_src: yes
    src: /usr/bin/ipmitool
    dest: /usr/bin/ipmitool.orig
    mode: 0644
  tags:
    - ipmitool-special

- name: Put in place the temporary OS-Inception IPMItool
  template:
    src: templates/ipmitool.j2
    dest: /usr/bin/ipmitool
    mode: 0755
    owner: root
    group: root
  tags:
    - ipmitool-special

- name: Replicate the SELinux context of ipmitool on the replacement shell
  command: "chcon --reference=/usr/bin/ipmitool.orig /usr/bin/ipmitool"
  tags:
    - ipmitool-special
