---
- name: Ensure {{ satellite_pkg }} is {{ new_state }}
  yum:
    name: "{{ satellite_pkg }}"
    state: "{{ new_state }}"
  become: true
  tags:
    - sub-man
    - undercloud

- name: Ensure OSPd registration to {{ satellite_url }} with activation key {{ activation_key }} is {{ new_state }}
  redhat_subscription:
    state: "{{ new_state }}"
    activationkey: "{{ activation_key }}"
    org_id: "{{ satellite_org }}"
    rhsm_baseurl: "{{ satellite_url }}"
  become: true
  tags:
    - sub-man
    - undercloud
    - rebuild

- name: Reinstall Satellite Certs after subscription
  shell: "/usr/bin/yum reinstall -e 0 -y {{ satellite_pkg }}"
  become: true
