---

  
# - name: Fetch UUID of the project {{ os_project }}
#   shell: "openstack --os-cloud {{ os_cluster_admincreds }} project show {{ os_project }} | awk '/ id / {print $4}'"
#   #environment: "{{ openstack_admin_auth_env }}"
#   register: project_id
#   when: configure_flavors==true
#   tags:
#     - flavor-access
#     - infrastructure

- name: Add access to custom flavors for project {{ os_project }}
  shell: "( nova flavor-access-list --flavor {{ item.value.name }} | grep -q {{ devcloud_project_id }} ) || nova flavor-access-add {{ item.value.name }} {{ devcloud_project_id }}"
  environment: "{{ openstack_admin_auth_env }}"
  with_dict: "{{ flavors }}"
  when: configure_flavors==true
  tags:
    - flavor-access
    - infrastructure
