- name: Ensure the directory for overcloud images is {{ new_state }}
  file:
    path: /home/{{ stack_user }}/images
    state: directory
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
#  when: new_state=="present"
  tags:
    - overcloud-images
    - undercloud

- name: Gather overcloud images
  unarchive:
    src: "{{item}}"
    dest: /home/stack/images/
    remote_src: yes
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0644
  with_items:
    "{{ overcloud_image_files }}"
#  when: new_state=="present"
  tags:
    - overcloud-images
    - undercloud

- name: Generate local mirror repo definition file
  template:
    src: "templates/localmirror.repo.j2"
    dest: "/home/{{ stack_user }}/images/localmirror.repo"
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0644
  tags:
    - customise-overcloud-image
    - undercloud

- name: Install libguestfs-tools-c to manipulate overcloud images
  yum:
    name: libguestfs-tools-c
    state: present
  tags:
    - customise-overcloud-image
    - undercloud

- name: Inject local mirror repo definition file
  shell: "virt-customize -a /home/stack/images/overcloud-full.qcow2 --copy-in /home/{{ stack_user }}/images/localmirror.repo:/etc/yum.repos.d"
  environment: 
    LIBGUESTFS_BACKEND: direct
  tags:
    - customise-overcloud-image
    - undercloud

- name: Ensure undercloud glance images are {{ new_state }}
  shell: "openstack overcloud image upload --image-path /home/stack/images/"
  become: yes
  become_user: stack
  environment: "{{ undercloud_auth_env_v2 }}"
  ignore_errors: true
  async: 120
  poll: 10
  tags:
    - overcloud-images
    - undercloud
