- name: Ensure undercloud config is {{ new_state }}
  template:
    src: undercloud.conf.j2
    dest: /home/{{ stack_user }}/undercloud.conf
#    state: "{{ new_state }}"
    owner: stack
    group: stack
    mode: 0644
  tags:
    - undercloud-config
    - undercloud
