---

- name: Import overcloud CA cert
  copy:
    dest: "/etc/pki/ca-trust/source/anchors/{{ os_project }}-ca.crt"
    content: "{{ hostvars[bastion_host]['clouddata']['SSL']['SSLRootCertificate'] }}"
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  tags:
    - overcloud-cacert-import

- name: Update CA trust
  shell: "update-ca-trust"
  become: true
  become_user: root
  tags:
    - overcloud-cacert-import

- name: create /etc/openstack/ directory
  file:
    dest: /etc/openstack/
    state: directory
    owner: root
    group: "{{ bastion_user_group }}"
    mode: 0775
  become: true
  become_user: root
  tags:
    - overcloud-cacert-import

- name: create symlink from /etc/pki/ca-trust/source/anchors/{{ os_project }}-ca.crt to /etc/openstack/cacert.pem for compatibility with stack-post-deploy
  file:
    src: "/etc/pki/ca-trust/source/anchors/{{ os_project }}-ca.crt"
    dest: "/etc/openstack/cacert.pem"
    state: link
  tags:
    - overcloud-cacert-import
