---
- name: Ensure support for fake_pxe in ironic is {{ new_state }}
  lineinfile:
    path: /etc/ironic/ironic.conf
    state: "{{ new_state }}"
    regexp: '^enabled_drivers\s'
    line: 'enabled_drivers = pxe_ipmitool,pxe_ssh,pxe_drac,pxe_ilo,fake_pxe'
  become: true
  notify:
    - restart_ironic
  tags:
    - ironic-config
    - undercloud
    - rebuild

- name: Move the ipmitool binary to a backup
  copy:
    remote_src: yes
    src: /usr/bin/ipmitool
    dest: /usr/bin/ipmitool.orig
    mode: 0644
  become: true
  tags:
    - ipmitool-special
    - undercloud
    - rebuild

- name: Put in place the temporary OS-Inception IPMItool
  template:
    src: "templates/ipmitool.v{{ hostvars['localhost']['clouds_yaml']['clouds'][os_cluster]['identity_api_version']}}.j2"
    dest: /usr/bin/ipmitool
    mode: 0755
    owner: root
    group: root
  become: true
  tags:
    - ipmitool-special
    - undercloud
    - rebuild

- name: Replicate the SELinux context of ipmitool on the replacement shell
  command: "chcon --reference=/usr/bin/ipmitool.orig /usr/bin/ipmitool"
  become: true
  tags:
    - ipmitool-special
    - undercloud
    - rebuild
