---
- name: Ensure neutron networks for {{ os_project }} are {{ new_state }}
  os_network:
    auth:
      auth_url: "{{ os_cluster_keystone_adminurl }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      project_name: "{{ os_project }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    project: "{{ os_project }}"
    name: "{{ item.value.name }}"
    port_security_enabled: "{{ item.value.port_security_enabled }}"
    endpoint_type: "{{ endpoint_type }}"
  when: item.value.use_existing == "false"
  with_dict: "{{ networks }}"
  tags:
    - networks
    - infrastructure
