---
- name: Ensuring {{ os_project }} keystone project is {{ new_state }}
  os_project:
    cloud: "{{ os_cluster_admincreds }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    endpoint_type: admin
    name: "{{ os_project }}"
    description: "{{ os_project}} project."
    domain_id: "{{ user_domain_id }}"
    enabled: true
  when: create_project==true
  tags: 
    - project
    - infrastructure
