---
- name: Create the deploy script
  template:
    src: "templates/deploy.sh.j2"
    dest: /home/{{ stack_user }}/deploy.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  tags:
    - deploy-script
    - templates
