---
- name: Ensure neutron networks for {{ os_project }} are {{ new_state }}
  os_network:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    name: "{{ item.value.name }}"
    port_security_enabled: "{{ item.value.port_security_enabled }}"
  when: item.value.use_existing == "false"
  with_dict: "{{ networks }}"
  tags: 
    - networks
    - infrastructure
