- name: Ensure {{ node_type }} instances for project {{ os_project }} are {{ new_state }} in the inventory
  add_host:
    hostname: "{{ prefix }}-{{ node_type }}-1"
    ansible_ssh_host: "{{ ospd_float }}"
    ansible_ssh_user: cloud-user
    ansible_become: true
    become_user: root
    become_method: sudo
    groups: 
      - "{{ node_type }}"
      - all
  
  tags:
    - inventory
    - core
    - undercloud
