---
- name: Ensure custom nova flavors for project {{ os_project }} are {{ new_state }}
  os_nova_flavor:
    cloud: "{{ os_cluster_admincreds }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    is_public: False
    name: "{{ item.value.name }}"
    ram: "{{ item.value.ram}}"
    vcpus: "{{ item.value.vcpus }}"
    disk: "{{ item.value.disk }}"
    ephemeral: "{{ item.value.ephemeral }}"
  with_dict: "{{ flavors }}"
  when: configure_flavors==true
  tags:
    - flavors
    - infrastructure
