---

- name: Create the ironic node preparation script
  template:
    src: "templates/prepare-ironic-nodes.sh.j2"
    dest: /home/{{ stack_user }}/prepare-ironic-nodes.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild

- name: Create the osp10 deploy script
  template:
    src: "templates/deploy.sh.j2"
    dest: /home/{{ stack_user }}/deploy.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild

- name: Create the osp10 keystone update script
  template:
    src: "templates/keystone-update.sh.j2"
    dest: /home/{{ stack_user }}/keystone-update.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild

- name: Create the osp10 nossl update script
  template:
    src: "templates/nossl-update.sh.j2"
    dest: /home/{{ stack_user }}/nossl-update.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild

- name: Create the osp10 overcloud update script
  template:
    src: "templates/osp10-overcloud-update.sh.j2"
    dest: /home/{{ stack_user }}/osp10-overcloud-update.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild


- name: Create the fast forward upgrade prepare script
  template:
    src: "templates/osp13-ffwd-upgrade-prepare.sh.j2"
    dest: /home/{{ stack_user }}/osp13-ffwd-upgrade-prepare.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild

- name: Create the fast forward upgrade converge script
  template:
    src: "templates/osp13-ffwd-upgrade-converge.sh.j2"
    dest: /home/{{ stack_user }}/osp13-ffwd-upgrade-converge.sh
    owner: "{{ stack_user }}"
    group: "{{ stack_user }}"
    mode: 0755
  become: true
  tags:
    - deploy-script
    - templates
    - rebuild
