---

- name: Get a json object containing instance networks
  shell: "openstack --os-cloud {{ os_cluster }} server list -c Name -f value"
  register: result
  tags:
    - always

- name: set the instance_network fact
  set_fact:
    instances: "{{ result.stdout_lines }}"
  tags:
   - always

- name: Dump all
  debug:
    var: instances | select('match', '.*pacemaker.*') | list | length
