---
- name: Ensure {{ node_type }} instances for project {{ os_project }} are present
  os_server:
    state: "present"
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    name: "{{ prefix}}-{{ node_type}}-{{ item }}"
    image: "{{ nodes[node_type].image }}"
    key_name: "{{ key_name }}"
    timeout: "{{ instance_creation_timeout }}"
    wait: "{{ nodes[node_type].wait }}"
    flavor: "{{ nodes[node_type].flavor }}"
    auto_ip: "{{ nodes[node_type].auto_ip }}"
    security_groups: "{{ nodes[node_type].secgroup }}"
    availability_zone: "{{ instance_az }}"
    nics:
      - port-name: "{{ prefix }}_provisioning_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_external_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_storage_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_internalapi_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_tenant_{{ node_type }}_{{ item }}"
    meta:
      group: "{{ node_type }}"
  with_sequence:
    count="{{nodes[node_type].count}}"
  when: instances | select('match', '.*service.*') | list | length < nodes.service.count and new_state=="present"
  tags:
    - instances
    - service-instances
    - infrastructure

- name: Ensure {{ node_type }} instances for project {{ os_project }} are absent
  os_server:
    state: "absent"
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    name: "{{ prefix}}-{{ node_type}}-{{ item }}"
    image: "{{ nodes[node_type].image }}"
    key_name: "{{ key_name }}"
    timeout: "{{ instance_creation_timeout }}"
    wait: "{{ nodes[node_type].wait }}"
    flavor: "{{ nodes[node_type].flavor }}"
    auto_ip: "{{ nodes[node_type].auto_ip }}"
    security_groups: "{{ nodes[node_type].secgroup }}"
    availability_zone: "{{ instance_az }}"
    nics:
      - port-name: "{{ prefix }}_provisioning_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_external_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_storage_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_internalapi_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_tenant_{{ node_type }}_{{ item }}"
    meta:
      group: "{{ node_type }}"
  with_sequence:
    count="{{nodes[node_type].count}}"
  when: new_state=="absent"
  tags:
    - instances
    - service-instances
    - infrastructure
