---
- name: Ensuring server affinity groups for {{ os_project }} are {{ new_state }}
  os_server_group:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    name: "{{ item }}"
    policies:
      - "{{ affinity_policy }}"
  when: use_affinity_groups == "true"
  with_items:
    - "{{ node_types }}" 
  tags: 
    - server-groups
    - infrastructure
