---

- name: Ensure ceph-ansible git repo checkout is present
  git:
    repo: "{{ git_repos.ceph_ansible.url }}"
    version: "{{ git_repos.ceph_ansible.branch }}"
    dest: "/home/{{ bastion_user }}/ceph-ansible"
    accept_hostkey: true
  ignore_errors: true
  tags:
    - git-clone
    - maxhammer
    - templates

- name: Ensure os-inception git repo checkout is present
  git:
    repo: "{{ git_repos.os_inception.url }}"
    version: "{{ git_repos.os_inception.branch }}"
    dest: "/home/{{ bastion_user }}/os-inception"
    accept_hostkey: true
  ignore_errors: true
  tags:
    - git-clone
    - maxhammer
    - templates
