---
- name: Ensure {{ os_inception_secgroup }} security group exists for project {{ os_project }} are {{ new_state }}
  os_security_group:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    name: "{{ os_inception_secgroup }}"
  tags:
    - secgroups
    - infrastructure
