---
- name: Ensure undercloud packages and dependencies are {{ new_state }}
  yum:
    name: "python-heat-agent"
    state: "{{ new_state }}"
  async: "{{ yum_timeout }}"
  poll: "{{ yum_poll }}"
  become: true
  tags:
    - overcloud-packages
    - preprovisioned-nodes
