- name: Ensure openstack client configuration directory is present
  file:
    name: ~/.config/openstack
    state: directory
  become: false

- name:  Ensure openstack client configuration is present
  template:
    src: clouds.yml.j2
    dest: ~/.config/openstack/clouds.yml
  become: false

- name: Ensure user credentials file is present
  template:
    src: ansiblerc.j2
    dest: ~/{{ os_project }}-{{ ansible_user }}rc
  become: false

- name: Ensure {{ cacertfile }} is present
  copy: 
    dest: "{{ cacertfile }}"
    content: "{{ cacert }}"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Ensure ssh configuration directory is present
  file:
    name: ~/.ssh
    state: directory
    mode: 0700
  become: false

- name: Ensure ssh configuration file is present
  template:
    src: config.j2
    dest: ~/.ssh/config
    mode: 0600
  become: false
