---
- name: Ensuring custom quota for project {{ os_project }} is {{ new_state }}
  os_quota:
    name: "{{ os_project }}"
    cores: "{{ quota.vcpus }}"
    ram: "{{ quota.ram }}"
    instances: "{{ quota.instances }}"
    port: "{{ quota.ports }}"
    state: "{{ new_state }}"
  when: create_project==true
  tags:
    - quota
    - infrastructure
