---
- name: Override port_security if use_existing_external_network is true
  shell: "for i in $(openstack --os-cloud {{ os_cluster }} port list --project {{ os_project }} | awk '/external/ {print $4}'); do openstack --os-cloud {{ os_cluster }} port set --disable-port-security $i; done;"
  #environment: "{{ openstack_user_auth_env }}"
  when: use_existing_external_network == "true"
  tags:
    - port-security
    - infrastructure
  ignore_errors: true

- name: Override port_security if use_existing_ceph is true
  shell: "for i in $(openstack --os-cloud {{ os_cluster }} port list --project {{ os_project }} | awk '/storage/ {print $4}'); do openstack --os-cloud {{ os_cluster }} port set --disable-port-security $i; done;"
  #environment: "{{ openstack_user_auth_env }}"
  when: use_existing_ceph == "true"
  tags:
    - port-security
    - infrastructure
  ignore_errors: true
