---
- name: Fetch default secgroup UUID
  shell: "openstack security group list --project os3 | awk '/default/ {print $2}'"
  environment: "{{ openstack_user_auth_env }}"
  register: default_secgroup_uuid
  ignore_errors: true
  when: new_state=="present"
  tags:
    - secgroups
    - infrastructure

- name: Ensure allow ssh rule in {{ os_inception_secgroup }} for {{ os_project }} is {{ new_state }}
  os_security_group_rule:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    security_group: "{{ default_secgroup_uuid.stdout }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  tags:
    - secgroups
    - infrastructure

- name: Ensure allow icmp rule in {{ os_inception_secgroup }} for {{ os_project }} is {{ new_state }}
  os_security_group_rule:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    security_group: "{{ default_secgroup_uuid.stdout }}"
    protocol: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  tags:
    - secgroups
    - infrastructure

#- name: Ensure allow secgroup traffic rule in {{ os_inception_secgroup }} for {{ os_project }} is {{ new_state }}
#  os_security_group_rule:
#    cloud: "{{ os_cluster }}"
#    cacert: "{{ cacertfile }}"
#    state: "{{ new_state }}"
#    security_group: "{{ os_inception_secgroup }}"
#    remote_group: "{{ os_inception_secgroup }}"
#  tags:
#    - secgroups
