- name: Run ceph-ansible
  shell: >
    set -o pipefail &&
    ansible-playbook -i hosts/inventory site.yml &>
    /home/{{ bastion_user }}/ceph_install.log
  args:
    chdir: ~/ceph-ansible
  tags:
    - ceph-ansible-run
