- name: Ensure Configuration git repo checkout is present
  git:
    repo: "{{ git_repos.config }}"
    dest: "/home/cloud-user/{{ config_repo }}"
    accept_hostkey: true
  tags: 
    - git-clone
    - templates
  

- name: Set up Configuration repo
  shell: "python setup.py sdist"
  args:
    chdir: "/home/cloud-user/{{ config_repo }}"
  tags: 
    - config-setup
    - templates
