- name: Ensure puppet_forge rubygem is {{ new_state }}
  gem:
    name: puppet_forge
    version: 2.2.6
    state: "{{ new_state }}"
    user_install: no
  become: yes
  when: gem_install==true
  tags:
    - puppetforge
    - r10k
    - templates
