---
- name: Ensure that the floating ip {{ ospd_float }} is {{ new_state }}
  shell: "( openstack floating ip list --project {{ os_project }} | grep -q {{ ospd_float }} ) || openstack floating ip create --floating-ip-address {{ ospd_float }} --project {{ os_project }} {{ external_network }}"
  environment: "{{ openstack_admin_auth_env }}"
  when: new_state=="present"
  tags:
    - ospd-float-create
    - infrastructure

- name: Ensure that the floating ip {{ ospd_float }} is {{ new_state }}
  shell: "openstack floating ip delete {{ ospd_float }}"
  environment: "{{ openstack_user_auth_env }}"
  ignore_errors: true
  when: new_state=="absent"
  tags:
    - ospd-float-create
    - infrastructure
