- name: Ensure openstack client configuration directory is present
  file:
    name: ~/.config/openstack
    state: directory
  become: false
  tags:
    - bastion-openstack-client

- name:  Ensure openstack client configuration is present
  template:
    src: clouds.yml.j2
    dest: ~/.config/openstack/clouds.yaml
  become: false
  tags:
    - bastion-openstack-client

- name: Ensure user credentials file is present
  template:
    src: ansiblerc.j2
    dest: ~/{{ os_project }}rc
  become: false
  tags:
    - bastion-openstack-client

- name: Ensure {{ cacertfile }} is present
  copy:
    dest: "{{ cacertfile }}"
    content: "{{ cacert }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - bastion-openstack-client

- name: Ensure ssh configuration directory is present
  file:
    name: ~/.ssh
    state: directory
    mode: 0700
  become: false
  tags:
    - bastion-openstack-client

# - name: Ensure ssh configuration file is present
#   template:
#     src: config.j2
#     dest: ~/.ssh/config
#     mode: 0600
#   become: false

- name: Ensure ssh configuration is present
  blockinfile:
    dest: ~/.ssh/config
    create: yes
    marker: "# {mark} overcloud network access "
    content: |
      Host "{{ networks.provisioning.cidr[:-4]+'*' }}"
      	User cloud-user
      	StrictHostKeyChecking no
      	UserKnownHostsFile=/dev/null
      	IdentityFile {{ key_file }}
      Host "{{ networks.external.cidr[:-4]+'*' }}"
      	User cloud-user
      	StrictHostKeyChecking no
      	UserKnownHostsFile=/dev/null
      	IdentityFile {{ key_file }}
      Host "{{ networks.storage.cidr[:-4]+'*' }}"
      	User cloud-user
      	StrictHostKeyChecking no
      	UserKnownHostsFile=/dev/null
      	IdentityFile {{ key_file }}
  become: false
  tags:
    - bastion-openstack-client
