---
# tasks file for 080-rhn-register
- include: overcloud-images.yml
- include: overcloud-containers.yml
  when: osp_version==13
- include: vendordata-container.yml
  when: osp_version==13 and use_vendordata|bool == true
