---

- name: create docker registry cacert directory
  file:
    dest: "/etc/docker/certs.d/{{ undercloud.container_registry }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true
  become_user: root
  when: undercloud.container_registry_encryption|bool == true
  tags:
    - overcloud-containers
    - undercloud
    - rebuild

- name: deploy docker registry CA cert
  copy:
    dest: "/etc/docker/certs.d/{{ undercloud.container_registry }}/ca.crt"
    content: "{{ underclound.container_registry_cacert }}"
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  when: undercloud.container_registry_encryption|bool == true
  tags:
    - overcloud-containers
    - undercloud
    - rebuild

- name: Prepare the overcloud container registry env file * images file.
  shell: >
    openstack overcloud container image prepare
    --namespace={{ undercloud.container_registry }}/{{ undercloud.container_project }}
    --push-destination={{ networks.provisioning.cidr_prefix }}.1:8787
    --prefix=openstack-  --tag-from-label {version}-{release}
    -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/neutron-ovn-dvr-ha.yaml
    --output-env-file=/home/stack/overcloud_images.yaml
    --output-images-file /home/stack/local_registry_images.yaml
  environment: "{{ undercloud_auth_env_v3 }}"
  args:
    chdir: /home/stack/images/
  become: yes
  become_user: stack
  poll: 10
  tags:
    - overcloud-containers
    - undercloud
    - rebuild

- name: Upload the overcloud containers into the undercloud registry
  shell: >
    openstack overcloud container image upload
    --config-file  /home/stack/local_registry_images.yaml
    --verbose
  environment: "{{ undercloud_auth_env_v3 }}"
  args:
    chdir: /home/stack/images/
  become: yes
  become_user: root
  poll: 10
  tags:
    - overcloud-containers
    - undercloud
    - rebuild
