---
- name: Ensure neutron subnets for project {{ os_project }} are {{ new_state}}
  os_subnet:
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    state: "{{ new_state }}"
    name: "{{ item.value.name }}"
    network_name: "{{ item.value.name }}"
    cidr: "{{ item.value.cidr }}"
    enable_dhcp: "{{ item.value.enable_dhcp }}"
    no_gateway_ip: "{{ item.value.no_gateway_ip }}"
    allocation_pool_start: "{{  item.value.cidr_prefix }}.{{  item.value.pool_start }}"
    allocation_pool_end: "{{  item.value.cidr_prefix }}.{{ item.value.pool_end }}"
  when: item.value.use_existing == "false"
  with_dict: "{{ networks }}"
  tags: 
    - subnets
    - infrastructure
