---
- name: Ensure python-novajoin package is installed
  yum:
    name: python-novajoin
    state: present
  become: true
  tags:
    - novajoin
    - undercloud-config
    - undercloud
    - rebuild

- name: Ensure undercloud config is {{ new_state }}
  template:
    src: novajoin_command.j2
    dest: /home/{{ stack_user }}/novajoin_command
    owner: stack
    group: stack
    mode: 0755
  become: true
  tags:
    - novajoin-command
    - novajoin
    - undercloud-config
    - undercloud
    - rebuild

- name: Retrieve IPA one-time-password for ospd enrolment
  shell: >
    /home/{{ stack_user }}/novajoin_command
  args:
    creates: /home/stack/ipaotp
  become: true
  tags:
    - novajoin
    - undercloud-config
    - undercloud
    - rebuild


- name: Load data
  slurp:
    src: "/home/stack/ipaotp"
  register: slurped_ipa_otp
  become: true
  tags:
    - novajoin
    - undercloud-config
    - undercloud
    - rebuild

- name: Load the ipa otp into a variable
  set_fact:
    novajoin_ipa_otp: "{{ slurped_ipa_otp.content | b64decode }}"
  become: true
  tags:
    - novajoin
    - undercloud-config
    - undercloud
    - rebuild

- name: Retrieve IPA host IP address for undercloud.conf
  set_fact:
    novajoin_ipa_ipaddr: "{{ lookup('dig', clouddata.Domains.IPA.url.split('/')[2]) }}"
