---
- name: Ensure osp13 undercloud packages and dependencies are present
  yum:
    name: ceph-ansible
    state: "{{ new_state }}"
  async: "{{ yum_timeout }}"
  poll: "{{ yum_poll }}"
  become: true
  tags:
    - tripleo-packages
    - undercloud
    - rebuild
