---
- name: Create virtual env for ansible
  pip:
   name: pip
   virtualenv: "~/.virtualenvs/{{ virtualenv_name }}"
   virtualenv_site_packages: yes

- name: Upgrade to a more recent version of pip
  pip:
    name: pip
    version: 18.0
    state: "{{ new_state }}"
    virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"

- name: upgrade setuptools in the virtualenv
  pip:
   name: setuptools
   state: latest
   virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"

- name: Ensure wrapt is {{ new_state }}
  pip:
    name: wrapt
    version: 1.10.0
    state: forcereinstall
    virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"

- name: Ensure python-openstackclient is {{ new_state }}
  pip:
    name: python-openstackclient
    state: forcereinstall
    virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"

- name: Ensure openstacksdk is {{ new_state }}
  pip:
    name: "{{ git_repos.openstacksdk.url }}@{{ git_repos.openstacksdk.branch }}"
    state: "{{ new_state }}"
    virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"

- name: Ensure ansible is {{ new_state }}
  pip:
    name: "{{ git_repos.ansible.url }}@{{ git_repos.ansible.branch }}"
    state: "{{ new_state }}"
    virtualenv:  "~/.virtualenvs/{{ virtualenv_name }}"
