---

- name:
  os_server_facts:
    auth:
      auth_url: "{{ os_cluster_keystone_adminurl }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      project_name: "{{ os_project }}"
    server: "{{ prefix}}-{{ node_type}}"
  tags:
    - bastion-instance
    - bastion-inventory

- debug:
    var: openstack_servers[0].interface_ip
  tags:
    - bastion-instance
    - bastion-facts

- name: set the bastion_float fact
  set_fact:
    bastion_float: "{{ openstack_servers[0].interface_ip }}"
  tags:
    - bastion-instance
    - bastion-inventory

- name: Ensure ssh confguration is present
  blockinfile:
    dest: ~/.ssh/config
    state: "{{ new_state }}"
    create: yes
    marker: "# {mark} {{ os_project }} access"
    content: |
      Host {{ bastion_float }}
        User {{ bastion_user }}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        IdentityFile ~/.ssh/id_rsa.osdev{{ os_project }}
      Host {{ prefix}}-{{ node_type}}.{{ domain_name }}
        User {{ bastion_user }}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        IdentityFile ~/.ssh/id_rsa.osdev{{ os_project }}
      Host {{ prefix}}-{{ node_type}}
        User {{ bastion_user }}
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
        IdentityFile ~/.ssh/id_rsa.osdev{{ os_project }}
  become: false
  tags:
    - bastion-instance
    - bastion-inventory

- name: Update /etc/hosts with bastion nodes
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ bastion_float }}.*'
    line: '{{ bastion_float }} {{ prefix}}-{{ node_type}}.{{ domain_name }} {{ prefix}}-{{ node_type}}'
    state: "{{ new_state }}"
  become: true
  tags:
    - bastion-inventory
    - bastion-instance

- name: Ensure the bastion instance is {{ new_state }} in the bastion group
  add_host:
    hostname: "{{ prefix}}-{{ node_type}}"
    ansible_ssh_host: "{{ bastion_float }}"
    ansible_ssh_user: cloud-user
    become_user: root
    become_method: sudo
    groups:
      - bastion
  tags:
    - bastion-instance
    - bastion-inventory

- name: Wait for the bastion instance to become accessable
  wait_for:
    port: 22
    host: "{{ bastion_float }}"
    search_regex: "OpenSSH"
    delay: 10
  tags:
    - bastion-instance
    - bastion-inventory
  when: new_state=='present'
