---
- name: Ensure {{ node_type }} instances for project {{ os_project }} are {{ new_state }}
  os_server:
    state: "{{ new_state }}"
    cloud: "{{ os_cluster }}"
    cacert: "{{ cacertfile }}"
    name: "{{ prefix}}-{{ node_type}}-{{ item }}"
    image: "{{ nodes[node_type].image }}"
    key_name: "{{ key_name }}"
    timeout: "{{ instance_creation_timeout }}"
    wait: "{{ instance_wait }}"
    flavor: "{{ nodes[node_type].flavor }}"
    security_groups: "{{ nodes[node_type].secgroup }}"
    availability_zone: "{{ instance_az }}"
    nics:
      - net-name: "{{ internal_network }}"
#      - port-name: "{{ prefix }}-provisioning-{{ node_type }}-{{ item }}"
      - port-name: "{{ prefix }}_storage_{{ node_type }}_{{ item }}"
      - port-name: "{{ prefix }}_storagemgmt_{{ node_type }}_{{ item }}"
    meta:
      group: "{{ node_type }}"
  when: use_existing_ceph == "false"
  with_sequence:
    count="{{ nodes[node_type].count }}"
  tags:
    - instances
    - ceph-instances
    - infrastructure
