---
- name: Copy instack.json to /home/stack on the undercloud
  copy:
    src: /tmp/nodes.json
    dest: /home/stack/instack.json
    owner: stack
    group: stack
    mode: 0644
#  when: new_state=="present"
  tags:
    - instack-copy
    - templates
