---
- name: Override port_security if use_existing_externa_network is true
  shell: "for i in $(openstack port list --project {{ os_project }} | awk '/external/ {print $4}'); do openstack port set --disable-port-security $i; done;"
  environment: "{{ openstack_user_auth_env }}"
  when: use_existing_external_network == "true"
  tags:
    - port-security
    - infrastructure
  ignore_errors: true

- name: Override port_security if use_existing_ceph is true
  shell: "for i in $(openstack port list --project {{ os_project }} | awk '/storage/ {print $4}'); do openstack port set --disable-port-security $i; done;"
  environment: "{{ openstack_user_auth_env }}"
  when: use_existing_ceph == "true"
  tags:
    - port-security
    - infrastructure
  ignore_errors: true
