---

- name: Get the clouddata from the bastion
  slurp:
    path: "{{ clouddata_path }}/{{ icloud_puppet_branch }}.yaml"
  register: encoded_clouddata
  tags:
    - clouddata

- name: load clouddata for the {{ os_project }} cloud into a cloud variable.
  set_fact:
    clouddata: "{{ encoded_clouddata.content|b64decode| from_yaml }}"
  no_log: true
  tags:
    - clouddata
